services:
  catalog:
    build: ../andesstay-ms-catalog
    ports:
      - "8081:8081"
  bff:
    build: .
    ports:
      - "8080:8080"
    environment:
      SECURITY_MODE: azure
      MS_CATALOG_URL: http://catalog:8081
      MS_RESERVATIONS_URL: http://reservations:8082
      AZURE_ISSUER_URI: https://login.microsoftonline.com/cb0b9f53-0ba7-4f09-8da2-c2f5ab4b73ee/v2.0
      AZURE_AUDIENCE: api://4cd6df9a-e2f7-4024-aea6-dd67c49709bc
    depends_on:
      - catalog
